### PR TITLE
Make username optional

### PR DESCRIPTION
**Pull request by Zizaco**
See #402

### CODE REVIEW

**Comment by lfolco** [comment]
Is this branch going to be merged into master?

**Comment by daparky** [comment]
I hope it is!

**Comment by danclaydonpm** [comment]
Just here to '+1' this branch, hoping it gets merged into master.

**Comment by furey** [comment]
+1 too please

**Comment by hardevine** [comment]
:+1:

**Comment by graystevens** [comment]
Was this not implemented recently via #475 ?

**Comment by furey** [comment]
@graystevens We're asking (hoping) for `username-optional` to be merged into `master`.

**Comment by Zizaco** [comment]
@furey It will me merged, soon.

**Comment by furey** [comment]
@Zizaco Looking forward to it. Cheers.

**Comment by GrahamCampbell** [comment]
This branch can be deleted from github now btw. :)

**Comment by atinder90** [comment]
Is it just me or anybody else still also having this issue ?

**Comment by janikvonrotz** [comment]
No, same here @atinder90

**Comment by digitaloutback** [comment]
Me too

**Comment by sumanta-ghosh** [comment]
Make username optional is not working. can you please explain the process in doc.

**Pull request merged**
